language: php
sudo: required
php:
  - 7.3
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - php artisan storage:link
  - php artisan config:clear
  - npm install npm@latest -g
  - npm install

script:
  - npm run prod
  - npm run prod
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml

after_failure:
  - cat storage/logs/laravel.log

after_success:
  - bash <(curl -s https://codecov.io/bash)
