language: php
php:
  - 7.3
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate
  - php artisan config:clear
  - npm install npm@latest -g
  - npm install

scripts:
  - vendor/bin/phpunit -c phpunit.xml