language: php
sudo: required

php:
  - 7.3
  - 7.2

addons:
  chrome: stable

before_install:
  - cp .env.testing .env
  - composer self-update
  - composer validate

install:
  - composer install --no-interaction --prefer-dist --no-suggest
  - npm install npm@latest -g
  - npm install

before_script:
  - php artisan key:generate
  - php artisan storage:link
  - php artisan dusk:chrome-driver
  - npm run prod
  - npm run prod
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml

after_failure:
  - cat storage/logs/laravel.log

after_success:
  - bash <(curl -s https://codecov.io/bash)
