language: php
php:
  - 7.3
  - 7.2

before_script:
  - composer install --no-interaction
  - cp .env.example .env

scripts:
  - php artisan key:generate
  - php artisan config:clear
  - vendor/bin/phpunit