version: '2'

services:

  #  The Application
  app:
    container_name: laravel_app
    image: esac/website:0.0.4
    volumes:
      - ./storage:/var/www/storage
#      - ./dump:/var/www/public/storage
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
#    ports:
#      - "700:700"
    entrypoint: php-fpm


  # The Web Server
  web:
    container_name: nginx_server
    image: esac_web:0.0.0
    volumes:
      - ./storage/logs/:/var/log/nginx
      - ./storage/app/public/:/var/www/public/storage
    ports:
      - 8990:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    container_name: esac_database
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

    # redis
  cache:
    image: redis:3.0-alpine

  # The Application
#  app:
#    build:
#      context: ""
#      dockerfile: ../local_app.dockerfile
#    working_dir: /var/www
#    container_name: esac_application
#    volumes:
#      - ../:/var/www
#    environment:
#      - "DB_PORT=3306"
#      - "DB_HOST=database"
#    ports:
#      - 80:8000
#    depends_on:
#      - "database"

volumes:
  dbdata: