version: '2'

services:

  #  The Application
  app:
    container_name: laravel_app
    volumes:
      - ./storage:/var/www/storage
      - laravel_public_folder:/var/www/public
    env_file:
      - ".env.example"
    environment:
      - "REDIS_HOST=cache"
    entrypoint: php-fpm

  # The Web Server
  web:
    container_name: nginx_server
    image: esac/nginx:dev
    env_file:
      - .env
    volumes:
      - laravel_public_folder:/var/www/public
      - ./storage/app/public/:/var/www/public/storage
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"



    #The Database
  database:
    image: mysql:5.7
    volumes:
      - esac_database:/var/lib/mysql
    container_name: esac_database
    env_file:
      - .env

    # redis
  cache:
    image: redis:3.0-alpine

volumes:
  esac_database:
  laravel_public_folder: