version: '2'

services:

  #  The Application
  app:
    container_name: laravel_app
    image: esac/website:0.0.9
    volumes:
      - ./storage:/var/www/storage
    env_file:
      - ".env.prod"
    environment:
      - "REDIS_HOST=cache"
    entrypoint: php-fpm

  # The Web Server
  web:
    container_name: nginx_server
    image: esac/nginx:0.0.5
    volumes:
      - ./storage/logs/:/var/log/nginx
      - ./storage/app/public/:/var/www/public/storage
    ports:
      - 8990:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    container_name: esac_database
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

    # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata: